#!/bin/bash

echo "#-----------------------------------------------------------------------#"
echo "The script it will run the virtual Evolved Packet Core "
echo "#-----------------------------------------------------------------------#"

cd ~/srsLTE/srsenb
sudo srsenb enb.conf
